// AUTO-GENERATED by scripts/build_v11_props.py
import type { NewsReelV11Props } from "./schema";

export const v11DefaultProps: NewsReelV11Props = {
  "kicker": "عاجل",
  "hookHeadline": "نص الكهرباء بس... وين الباقي؟",
  "vo": "vo/2026-07-03-v11-golden-iraq-grid/vo.mp3",
  "audioBed": "audio/mood_newsroom.mp3",
  "bedVolume": 0.16,
  "shots": [
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/hero.jpg",
      "startF": 0,
      "durationF": 95,
      "fromScale": 1.06,
      "toScale": 1.24,
      "fromX": 0.0,
      "fromY": 0.0,
      "toX": 0.0,
      "toY": -0.35
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_1.jpg",
      "startF": 95,
      "durationF": 100,
      "fromScale": 1.28,
      "toScale": 1.1,
      "fromX": -0.4,
      "fromY": 0.2,
      "toX": 0.3,
      "toY": 0.0
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_2.jpg",
      "startF": 195,
      "durationF": 80,
      "fromScale": 1.1,
      "toScale": 1.3,
      "fromX": 0.35,
      "fromY": -0.2,
      "toX": -0.3,
      "toY": 0.15
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_3.jpg",
      "startF": 275,
      "durationF": 105,
      "fromScale": 1.32,
      "toScale": 1.12,
      "fromX": 0.0,
      "fromY": -0.4,
      "toX": 0.0,
      "toY": 0.3
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/hero.jpg",
      "startF": 380,
      "durationF": 89,
      "fromScale": 1.08,
      "toScale": 1.26,
      "fromX": -0.3,
      "fromY": -0.25,
      "toX": 0.35,
      "toY": 0.2
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_1.jpg",
      "startF": 469,
      "durationF": 87,
      "fromScale": 1.26,
      "toScale": 1.08,
      "fromX": 0.3,
      "fromY": 0.3,
      "toX": -0.25,
      "toY": -0.2
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_2.jpg",
      "startF": 556,
      "durationF": 76,
      "fromScale": 1.06,
      "toScale": 1.24,
      "fromX": 0.0,
      "fromY": 0.0,
      "toX": 0.0,
      "toY": -0.35
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_3.jpg",
      "startF": 632,
      "durationF": 107,
      "fromScale": 1.28,
      "toScale": 1.1,
      "fromX": -0.4,
      "fromY": 0.2,
      "toX": 0.3,
      "toY": 0.0
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/hero.jpg",
      "startF": 739,
      "durationF": 111,
      "fromScale": 1.1,
      "toScale": 1.3,
      "fromX": 0.35,
      "fromY": -0.2,
      "toX": -0.3,
      "toY": 0.15
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_1.jpg",
      "startF": 850,
      "durationF": 78,
      "fromScale": 1.32,
      "toScale": 1.12,
      "fromX": 0.0,
      "fromY": -0.4,
      "toX": 0.0,
      "toY": 0.3
    },
    {
      "img": "images/news/2026-06-30-iraq-grid-summer-deficit/broll_2.jpg",
      "startF": 928,
      "durationF": 164,
      "fromScale": 1.08,
      "toScale": 1.26,
      "fromX": -0.3,
      "fromY": -0.25,
      "toX": 0.35,
      "toY": 0.2
    }
  ],
  "lines": [
    {
      "words": [
        {
          "word": "نصف",
          "startF": 3,
          "endF": 14
        },
        {
          "word": "الكهرباء",
          "startF": 14,
          "endF": 31
        },
        {
          "word": "فقط",
          "startF": 31,
          "endF": 42
        }
      ],
      "startF": 3,
      "endF": 42
    },
    {
      "words": [
        {
          "word": "هذا",
          "startF": 66,
          "endF": 76
        },
        {
          "word": "ما",
          "startF": 76,
          "endF": 80
        },
        {
          "word": "تستطيع",
          "startF": 80,
          "endF": 95
        },
        {
          "word": "الشبكة",
          "startF": 95,
          "endF": 110
        },
        {
          "word": "العراقية",
          "startF": 110,
          "endF": 129
        }
      ],
      "startF": 66,
      "endF": 129
    },
    {
      "words": [
        {
          "word": "توليده",
          "startF": 129,
          "endF": 146
        },
        {
          "word": "هذا",
          "startF": 146,
          "endF": 156
        },
        {
          "word": "الصيف",
          "startF": 156,
          "endF": 170
        }
      ],
      "startF": 129,
      "endF": 170
    },
    {
      "words": [
        {
          "word": "الطلب",
          "startF": 195,
          "endF": 209
        },
        {
          "word": "يتجاوز",
          "startF": 209,
          "endF": 228
        },
        {
          "word": "خمسين",
          "startF": 228,
          "endF": 241
        },
        {
          "word": "ألف",
          "startF": 241,
          "endF": 248
        },
        {
          "word": "ميغاواط",
          "startF": 248,
          "endF": 265
        }
      ],
      "startF": 195,
      "endF": 265
    },
    {
      "words": [
        {
          "word": "والتوليد",
          "startF": 275,
          "endF": 292
        },
        {
          "word": "لا",
          "startF": 292,
          "endF": 296
        },
        {
          "word": "يتعدى",
          "startF": 296,
          "endF": 309
        },
        {
          "word": "ثمانية",
          "startF": 309,
          "endF": 326
        },
        {
          "word": "وعشرين",
          "startF": 326,
          "endF": 342
        }
      ],
      "startF": 275,
      "endF": 342
    },
    {
      "words": [
        {
          "word": "ألفاً",
          "startF": 342,
          "endF": 355
        }
      ],
      "startF": 342,
      "endF": 355
    },
    {
      "words": [
        {
          "word": "والأغرب",
          "startF": 380,
          "endF": 399
        }
      ],
      "startF": 380,
      "endF": 399
    },
    {
      "words": [
        {
          "word": "الوزارة",
          "startF": 424,
          "endF": 442
        },
        {
          "word": "تصرف",
          "startF": 442,
          "endF": 453
        },
        {
          "word": "ستمئة",
          "startF": 453,
          "endF": 469
        },
        {
          "word": "مليار",
          "startF": 469,
          "endF": 481
        },
        {
          "word": "دينار",
          "startF": 482,
          "endF": 495
        }
      ],
      "startF": 424,
      "endF": 495
    },
    {
      "words": [
        {
          "word": "شهرياً",
          "startF": 495,
          "endF": 513
        },
        {
          "word": "لكنها",
          "startF": 524,
          "endF": 540
        },
        {
          "word": "لا",
          "startF": 540,
          "endF": 544
        },
        {
          "word": "تحصّل",
          "startF": 544,
          "endF": 556
        },
        {
          "word": "سوى",
          "startF": 556,
          "endF": 564
        }
      ],
      "startF": 495,
      "endF": 564
    },
    {
      "words": [
        {
          "word": "واحد",
          "startF": 564,
          "endF": 575
        },
        {
          "word": "بالمئة",
          "startF": 575,
          "endF": 589
        },
        {
          "word": "من",
          "startF": 589,
          "endF": 593
        },
        {
          "word": "قيمة",
          "startF": 593,
          "endF": 606
        },
        {
          "word": "الكهرباء",
          "startF": 606,
          "endF": 623
        }
      ],
      "startF": 564,
      "endF": 623
    },
    {
      "words": [
        {
          "word": "التي",
          "startF": 624,
          "endF": 631
        },
        {
          "word": "تبيعها",
          "startF": 632,
          "endF": 650
        }
      ],
      "startF": 624,
      "endF": 650
    },
    {
      "words": [
        {
          "word": "وواردات",
          "startF": 676,
          "endF": 695
        },
        {
          "word": "الغاز",
          "startF": 695,
          "endF": 707
        },
        {
          "word": "الإيراني",
          "startF": 707,
          "endF": 722
        },
        {
          "word": "انخفضت",
          "startF": 723,
          "endF": 739
        },
        {
          "word": "إلى",
          "startF": 739,
          "endF": 746
        }
      ],
      "startF": 676,
      "endF": 746
    },
    {
      "words": [
        {
          "word": "أقل",
          "startF": 746,
          "endF": 757
        },
        {
          "word": "من",
          "startF": 757,
          "endF": 760
        },
        {
          "word": "نصف",
          "startF": 760,
          "endF": 769
        },
        {
          "word": "الحاجة",
          "startF": 769,
          "endF": 782
        },
        {
          "word": "بعد",
          "startF": 782,
          "endF": 790
        }
      ],
      "startF": 746,
      "endF": 790
    },
    {
      "words": [
        {
          "word": "ضربات",
          "startF": 790,
          "endF": 803
        },
        {
          "word": "حقل",
          "startF": 803,
          "endF": 812
        },
        {
          "word": "بارس",
          "startF": 812,
          "endF": 824
        }
      ],
      "startF": 790,
      "endF": 824
    },
    {
      "words": [
        {
          "word": "فمن",
          "startF": 850,
          "endF": 857
        },
        {
          "word": "يدفع",
          "startF": 858,
          "endF": 870
        },
        {
          "word": "ثمن",
          "startF": 870,
          "endF": 879
        },
        {
          "word": "هذا",
          "startF": 879,
          "endF": 890
        },
        {
          "word": "العجز",
          "startF": 890,
          "endF": 902
        }
      ],
      "startF": 850,
      "endF": 902
    },
    {
      "words": [
        {
          "word": "وهل",
          "startF": 928,
          "endF": 938
        },
        {
          "word": "يمر",
          "startF": 938,
          "endF": 950
        },
        {
          "word": "صيف",
          "startF": 950,
          "endF": 960
        },
        {
          "word": "بغداد",
          "startF": 960,
          "endF": 973
        },
        {
          "word": "بسلام",
          "startF": 973,
          "endF": 990
        }
      ],
      "startF": 928,
      "endF": 990
    }
  ],
  "statPops": [
    {
      "value": "50,000",
      "labelArabic": "ميغاواط — ذروة الطلب",
      "atFrame": 226,
      "holdFrames": 75
    },
    {
      "value": "1%",
      "labelArabic": "نسبة تحصيل فواتير الكهرباء",
      "atFrame": 562,
      "holdFrames": 75
    }
  ],
  "endQuestion": "هل يمر صيف بغداد بسلام؟",
  "handle": "@photonect.news",
  "sourcesLine": "المصادر: مرصد إيكو عراق · شفق نيوز · كردستان 24",
  "totalFrames": 1092
};
