// AUTO-GENERATED by scripts/tenants/cha_dude/build_chat_props.py
import type { ChatReelProps } from "./schema";

export const chatDefaultProps: ChatReelProps = {
  "hook": "11 بالليل ومريض يسأل… منو يرد؟",
  "hookFrames": 78,
  "contactName": "چا دود",
  "avatarLetter": "چ",
  "statusLine": "متصل الآن",
  "clockLabel": "23:41",
  "turns": [
    {
      "who": "customer",
      "text": "السلام عليكم، عندي عيادة اسنان بالمنصور",
      "time": "23:41",
      "startF": 78
    },
    {
      "who": "agent",
      "text": "وعليكم السلام دكتور 🙏 آني «چا دود» — مساعد ذكاء اصطناعي من فوتونكت، أرد على زباين المحلات 24 ساعة حتى بعد 10 بالليل وبالجمعة.\n\nخلّي أوريك بنفسي شلون أرد على مريض يريد يحجز: اكتبلي سؤال كأنك مريض يسأل عيادتك.",
      "time": "23:41",
      "startF": 174,
      "typingF": 78,
      "latencyS": 2.6
    },
    {
      "who": "customer",
      "text": "زين خلي اجرب. شكد التنظيف؟ وعدكم الخميس؟",
      "time": "23:41",
      "startF": 354
    },
    {
      "who": "agent",
      "text": "🎭 مثال: عيادة المثال — التنظيف 35 ألف (رقم للمثال بس)، والخميس الدكتور موجود من 4 للـ 9 بالليل. تريد أسجّل اسمك للخميس؟ (بالتجربة ما ينرسل شي فعلاً)",
      "time": "23:42",
      "startF": 441,
      "typingF": 69,
      "latencyS": 2.3
    },
    {
      "who": "customer",
      "text": "انت بوت لو انسان؟",
      "time": "23:42",
      "startF": 621
    },
    {
      "who": "agent",
      "text": "آني «چا دود» — مساعد ذكاء اصطناعي من فوتونكت، مو إنسان 🤖 إذا تحب واحد من الفريق يحچي وياك، گلّي وأبلّغهم.",
      "time": "23:42",
      "startF": 651,
      "typingF": 12,
      "latencyS": 0.0
    }
  ],
  "stopwatchOnFirst": true,
  "endcard": {
    "title": "چا دود… يرد 24 ساعة",
    "sub": "من فوتونكت — موظفة رد ما تنام ولا تتأخر",
    "number": "0773 894 0795",
    "cta": "دزها لصاحب عيادة تعرفه",
    "small": "محادثة حقيقية، الردود بدون تعديل، الثواني مقاسة"
  },
  "endcardStartF": 843,
  "voClips": [
    {
      "src": "vo/chadude/a_open/vo.mp3",
      "atF": 0
    },
    {
      "src": "vo/chadude/a_close/vo.mp3",
      "atF": 819
    }
  ],
  "bed": "",
  "bedVolume": 0.1,
  "sfx": true,
  "totalFrames": 1219
};
