// AUTO-GENERATED by scripts/build_vox_props.py
import type { VoxReelProps } from "./schema";

export const voxDefaultProps: VoxReelProps = {
  "titleArabic": "ليش الدولار بالعراق بسعرين؟",
  "vo": "vo/dollar-two-rates/vo.mp3",
  "audioBed": "audio/mood_newsroom.mp3",
  "bedVolume": 0.14,
  "blocks": [
    {
      "arabicVo": "خفّضت موازنة 2026 سعر صرف الدولار إلى 1,300 دينار. وفي الأشهر ذاتها صعد سعر السوق من 1,433 إلى 1,554.",
      "collage": "vox/dollar-two-rates/block_1.jpg",
      "bg": "#F2E4C9",
      "accent": "#FFC217",
      "startF": 0,
      "durationF": 462,
      "pushIn": 0.09,
      "driftX": -0.02,
      "annotations": [
        {
          "kind": "arrow",
          "atFrame": 254,
          "drawFrames": 15,
          "x": 0.5,
          "y": 0.52,
          "w": 0.5,
          "h": 0.3,
          "color": "#0A0A10"
        }
      ],
      "throughline": 0.167
    },
    {
      "arabicVo": "السعر الرسمي 1,320 دينار، والسوق فوق 1,500. المسافر يشتري ألفي دولار بالسعر الرسمي شهرياً، وما زاد يشتريه من السوق.",
      "collage": "vox/dollar-two-rates/block_2.jpg",
      "bg": "#E8DCC8",
      "accent": "#D72638",
      "startF": 462,
      "durationF": 405,
      "pushIn": 0.11,
      "driftX": 0.02,
      "annotations": [
        {
          "kind": "circle",
          "atFrame": 222,
          "drawFrames": 15,
          "x": 0.62,
          "y": 0.5,
          "w": 0.42,
          "h": 0.26,
          "color": "#0A0A10"
        }
      ],
      "throughline": 0.333
    },
    {
      "arabicVo": "هيأة الإحصاء العراقية تنشر متوسط السوق شهرياً: 1,532 في النصف الأول، مقابل 1,444 في عام 2025.",
      "collage": "vox/dollar-two-rates/block_3.jpg",
      "bg": "#1B2A44",
      "accent": "#FFC217",
      "startF": 867,
      "durationF": 414,
      "pushIn": 0.13,
      "driftX": 0,
      "annotations": [
        {
          "kind": "underline",
          "atFrame": 227,
          "drawFrames": 15,
          "x": 0.5,
          "y": 0.78,
          "w": 0.56,
          "h": 0.16,
          "color": "#FFC217"
        }
      ],
      "throughline": 0.5,
      "bars": {
        "atFrame": 144,
        "values": [
          0.48,
          0.56,
          0.72,
          0.66,
          0.63,
          0.78
        ],
        "x": 0.5,
        "y": 0.72,
        "w": 0.5,
        "h": 0.2,
        "color": "#FFC217"
      }
    },
    {
      "arabicVo": "مُنع نحو 27 مصرفاً عراقياً من التعامل بالدولار خلال ثلاث سنوات، بحسب رويترز. ومنذ 2022 تمر التحويلات عبر قنوات تكشف المستفيد النهائي.",
      "collage": "vox/dollar-two-rates/block_4.jpg",
      "bg": "#F0E0CD",
      "accent": "#D72638",
      "startF": 1281,
      "durationF": 443,
      "pushIn": 0.09,
      "driftX": -0.02,
      "annotations": [
        {
          "kind": "bracket",
          "atFrame": 243,
          "drawFrames": 15,
          "x": 0.5,
          "y": 0.46,
          "w": 0.56,
          "h": 0.4,
          "color": "#0A0A10"
        }
      ],
      "throughline": 0.667
    },
    {
      "arabicVo": "لكن الفجوة اتسعت أكثر مع تفعيل نظام أسيكودا الجمركي مطلع 2026؛ تجار تحوّلوا إلى السوق الموازية، والكلفة انتقلت إلى المستهلك، بحسب تحقيق جمار.",
      "collage": "vox/dollar-two-rates/block_5.jpg",
      "bg": "#2A1E2E",
      "accent": "#FFC217",
      "startF": 1724,
      "durationF": 431,
      "pushIn": 0.11,
      "driftX": 0.02,
      "annotations": [
        {
          "kind": "arrow",
          "atFrame": 237,
          "drawFrames": 15,
          "x": 0.5,
          "y": 0.62,
          "w": 0.5,
          "h": 0.3,
          "color": "#FFC217"
        }
      ],
      "throughline": 0.833
    },
    {
      "arabicVo": "البنك المركزي قال في شباط إنه لا ينوي تغيير السعر، وتغيّر محافظه في حزيران. يبقى رقمان: الرسمي قرار يُتخذ، وسعر السوق جواب يُقاس.",
      "collage": "vox/dollar-two-rates/block_6.jpg",
      "bg": "#F2E4C9",
      "accent": "#D72638",
      "startF": 2155,
      "durationF": 483,
      "pushIn": 0.13,
      "driftX": 0,
      "annotations": [
        {
          "kind": "circle",
          "atFrame": 265,
          "drawFrames": 15,
          "x": 0.5,
          "y": 0.46,
          "w": 0.46,
          "h": 0.3,
          "color": "#0A0A10"
        }
      ],
      "throughline": 1.0
    }
  ],
  "lines": [
    {
      "words": [
        {
          "word": "خفّضت",
          "startF": 3,
          "endF": 19
        },
        {
          "word": "موازنة",
          "startF": 20,
          "endF": 38
        },
        {
          "word": "2026",
          "startF": 38,
          "endF": 82
        },
        {
          "word": "سعر",
          "startF": 83,
          "endF": 93
        }
      ],
      "startF": 3,
      "endF": 93
    },
    {
      "words": [
        {
          "word": "صرف",
          "startF": 93,
          "endF": 101
        },
        {
          "word": "الدولار",
          "startF": 102,
          "endF": 116
        },
        {
          "word": "إلى",
          "startF": 116,
          "endF": 123
        },
        {
          "word": "1,300",
          "startF": 123,
          "endF": 159
        }
      ],
      "startF": 93,
      "endF": 159
    },
    {
      "words": [
        {
          "word": "دينار",
          "startF": 159,
          "endF": 179
        }
      ],
      "startF": 159,
      "endF": 179
    },
    {
      "words": [
        {
          "word": "وفي",
          "startF": 204,
          "endF": 212
        },
        {
          "word": "الأشهر",
          "startF": 213,
          "endF": 227
        },
        {
          "word": "ذاتها",
          "startF": 227,
          "endF": 241
        },
        {
          "word": "صعد",
          "startF": 242,
          "endF": 253
        }
      ],
      "startF": 204,
      "endF": 253
    },
    {
      "words": [
        {
          "word": "سعر",
          "startF": 253,
          "endF": 261
        },
        {
          "word": "السوق",
          "startF": 261,
          "endF": 274
        },
        {
          "word": "من",
          "startF": 274,
          "endF": 279
        },
        {
          "word": "1,433",
          "startF": 279,
          "endF": 353
        }
      ],
      "startF": 253,
      "endF": 353
    },
    {
      "words": [
        {
          "word": "إلى",
          "startF": 353,
          "endF": 360
        },
        {
          "word": "1,554",
          "startF": 361,
          "endF": 436
        }
      ],
      "startF": 353,
      "endF": 436
    },
    {
      "words": [
        {
          "word": "السعر",
          "startF": 462,
          "endF": 474
        },
        {
          "word": "الرسمي",
          "startF": 474,
          "endF": 489
        },
        {
          "word": "1,320",
          "startF": 490,
          "endF": 545
        },
        {
          "word": "دينار",
          "startF": 545,
          "endF": 565
        }
      ],
      "startF": 462,
      "endF": 565
    },
    {
      "words": [
        {
          "word": "والسوق",
          "startF": 570,
          "endF": 588
        },
        {
          "word": "فوق",
          "startF": 589,
          "endF": 599
        },
        {
          "word": "1,500",
          "startF": 599,
          "endF": 634
        }
      ],
      "startF": 570,
      "endF": 634
    },
    {
      "words": [
        {
          "word": "المسافر",
          "startF": 660,
          "endF": 682
        },
        {
          "word": "يشتري",
          "startF": 682,
          "endF": 697
        },
        {
          "word": "ألفي",
          "startF": 697,
          "endF": 710
        },
        {
          "word": "دولار",
          "startF": 711,
          "endF": 725
        }
      ],
      "startF": 660,
      "endF": 725
    },
    {
      "words": [
        {
          "word": "بالسعر",
          "startF": 726,
          "endF": 736
        },
        {
          "word": "الرسمي",
          "startF": 737,
          "endF": 751
        },
        {
          "word": "شهرياً",
          "startF": 752,
          "endF": 773
        },
        {
          "word": "وما",
          "startF": 780,
          "endF": 789
        }
      ],
      "startF": 726,
      "endF": 789
    },
    {
      "words": [
        {
          "word": "زاد",
          "startF": 789,
          "endF": 797
        },
        {
          "word": "يشتريه",
          "startF": 798,
          "endF": 817
        },
        {
          "word": "من",
          "startF": 817,
          "endF": 823
        },
        {
          "word": "السوق",
          "startF": 823,
          "endF": 841
        }
      ],
      "startF": 789,
      "endF": 841
    },
    {
      "words": [
        {
          "word": "هيأة",
          "startF": 867,
          "endF": 878
        },
        {
          "word": "الإحصاء",
          "startF": 878,
          "endF": 891
        },
        {
          "word": "العراقية",
          "startF": 891,
          "endF": 913
        },
        {
          "word": "تنشر",
          "startF": 914,
          "endF": 927
        }
      ],
      "startF": 867,
      "endF": 927
    },
    {
      "words": [
        {
          "word": "متوسط",
          "startF": 928,
          "endF": 950
        },
        {
          "word": "السوق",
          "startF": 950,
          "endF": 963
        },
        {
          "word": "شهرياً",
          "startF": 963,
          "endF": 985
        },
        {
          "word": "1,532",
          "startF": 992,
          "endF": 1064
        }
      ],
      "startF": 928,
      "endF": 1064
    },
    {
      "words": [
        {
          "word": "في",
          "startF": 1064,
          "endF": 1066
        },
        {
          "word": "النصف",
          "startF": 1067,
          "endF": 1076
        },
        {
          "word": "الأول",
          "startF": 1076,
          "endF": 1094
        },
        {
          "word": "مقابل",
          "startF": 1101,
          "endF": 1117
        }
      ],
      "startF": 1064,
      "endF": 1117
    },
    {
      "words": [
        {
          "word": "1,444",
          "startF": 1117,
          "endF": 1186
        },
        {
          "word": "في",
          "startF": 1187,
          "endF": 1192
        },
        {
          "word": "عام",
          "startF": 1193,
          "endF": 1201
        },
        {
          "word": "2025",
          "startF": 1201,
          "endF": 1255
        }
      ],
      "startF": 1117,
      "endF": 1255
    },
    {
      "words": [
        {
          "word": "مُنع",
          "startF": 1281,
          "endF": 1292
        },
        {
          "word": "نحو",
          "startF": 1292,
          "endF": 1301
        },
        {
          "word": "27",
          "startF": 1302,
          "endF": 1330
        },
        {
          "word": "مصرفاً",
          "startF": 1330,
          "endF": 1346
        }
      ],
      "startF": 1281,
      "endF": 1346
    },
    {
      "words": [
        {
          "word": "عراقياً",
          "startF": 1346,
          "endF": 1364
        },
        {
          "word": "من",
          "startF": 1364,
          "endF": 1368
        },
        {
          "word": "التعامل",
          "startF": 1369,
          "endF": 1387
        },
        {
          "word": "بالدولار",
          "startF": 1387,
          "endF": 1403
        }
      ],
      "startF": 1346,
      "endF": 1403
    },
    {
      "words": [
        {
          "word": "خلال",
          "startF": 1403,
          "endF": 1416
        },
        {
          "word": "ثلاث",
          "startF": 1416,
          "endF": 1429
        },
        {
          "word": "سنوات",
          "startF": 1429,
          "endF": 1451
        },
        {
          "word": "بحسب",
          "startF": 1455,
          "endF": 1474
        }
      ],
      "startF": 1403,
      "endF": 1474
    },
    {
      "words": [
        {
          "word": "رويترز",
          "startF": 1474,
          "endF": 1496
        }
      ],
      "startF": 1474,
      "endF": 1496
    },
    {
      "words": [
        {
          "word": "ومنذ",
          "startF": 1522,
          "endF": 1537
        },
        {
          "word": "2022",
          "startF": 1537,
          "endF": 1586
        },
        {
          "word": "تمر",
          "startF": 1586,
          "endF": 1596
        },
        {
          "word": "التحويلات",
          "startF": 1596,
          "endF": 1617
        }
      ],
      "startF": 1522,
      "endF": 1617
    },
    {
      "words": [
        {
          "word": "عبر",
          "startF": 1618,
          "endF": 1627
        },
        {
          "word": "قنوات",
          "startF": 1627,
          "endF": 1646
        },
        {
          "word": "تكشف",
          "startF": 1647,
          "endF": 1658
        },
        {
          "word": "المستفيد",
          "startF": 1659,
          "endF": 1677
        }
      ],
      "startF": 1618,
      "endF": 1677
    },
    {
      "words": [
        {
          "word": "النهائي",
          "startF": 1678,
          "endF": 1699
        }
      ],
      "startF": 1678,
      "endF": 1699
    },
    {
      "words": [
        {
          "word": "لكن",
          "startF": 1724,
          "endF": 1738
        },
        {
          "word": "الفجوة",
          "startF": 1738,
          "endF": 1753
        },
        {
          "word": "اتسعت",
          "startF": 1753,
          "endF": 1768
        },
        {
          "word": "أكثر",
          "startF": 1768,
          "endF": 1782
        }
      ],
      "startF": 1724,
      "endF": 1782
    },
    {
      "words": [
        {
          "word": "مع",
          "startF": 1782,
          "endF": 1787
        },
        {
          "word": "تفعيل",
          "startF": 1788,
          "endF": 1802
        },
        {
          "word": "نظام",
          "startF": 1802,
          "endF": 1813
        },
        {
          "word": "أسيكودا",
          "startF": 1814,
          "endF": 1830
        }
      ],
      "startF": 1782,
      "endF": 1830
    },
    {
      "words": [
        {
          "word": "الجمركي",
          "startF": 1830,
          "endF": 1851
        },
        {
          "word": "مطلع",
          "startF": 1851,
          "endF": 1865
        },
        {
          "word": "2026",
          "startF": 1865,
          "endF": 1916
        },
        {
          "word": "تجار",
          "startF": 1923,
          "endF": 1939
        }
      ],
      "startF": 1830,
      "endF": 1939
    },
    {
      "words": [
        {
          "word": "تحوّلوا",
          "startF": 1940,
          "endF": 1956
        },
        {
          "word": "إلى",
          "startF": 1956,
          "endF": 1962
        },
        {
          "word": "السوق",
          "startF": 1962,
          "endF": 1973
        },
        {
          "word": "الموازية",
          "startF": 1973,
          "endF": 1999
        }
      ],
      "startF": 1940,
      "endF": 1999
    },
    {
      "words": [
        {
          "word": "والكلفة",
          "startF": 2005,
          "endF": 2024
        },
        {
          "word": "انتقلت",
          "startF": 2024,
          "endF": 2041
        },
        {
          "word": "إلى",
          "startF": 2041,
          "endF": 2046
        },
        {
          "word": "المستهلك",
          "startF": 2046,
          "endF": 2071
        }
      ],
      "startF": 2005,
      "endF": 2071
    },
    {
      "words": [
        {
          "word": "بحسب",
          "startF": 2077,
          "endF": 2095
        },
        {
          "word": "تحقيق",
          "startF": 2096,
          "endF": 2112
        },
        {
          "word": "جمار",
          "startF": 2112,
          "endF": 2129
        }
      ],
      "startF": 2077,
      "endF": 2129
    },
    {
      "words": [
        {
          "word": "البنك",
          "startF": 2155,
          "endF": 2168
        },
        {
          "word": "المركزي",
          "startF": 2169,
          "endF": 2188
        },
        {
          "word": "قال",
          "startF": 2188,
          "endF": 2197
        },
        {
          "word": "في",
          "startF": 2197,
          "endF": 2201
        }
      ],
      "startF": 2155,
      "endF": 2201
    },
    {
      "words": [
        {
          "word": "شباط",
          "startF": 2201,
          "endF": 2215
        },
        {
          "word": "إنه",
          "startF": 2215,
          "endF": 2228
        },
        {
          "word": "لا",
          "startF": 2228,
          "endF": 2232
        },
        {
          "word": "ينوي",
          "startF": 2232,
          "endF": 2243
        }
      ],
      "startF": 2201,
      "endF": 2243
    },
    {
      "words": [
        {
          "word": "تغيير",
          "startF": 2243,
          "endF": 2255
        },
        {
          "word": "السعر",
          "startF": 2256,
          "endF": 2272
        },
        {
          "word": "وتغيّر",
          "startF": 2278,
          "endF": 2298
        },
        {
          "word": "محافظه",
          "startF": 2299,
          "endF": 2321
        }
      ],
      "startF": 2243,
      "endF": 2321
    },
    {
      "words": [
        {
          "word": "في",
          "startF": 2321,
          "endF": 2325
        },
        {
          "word": "حزيران",
          "startF": 2326,
          "endF": 2349
        }
      ],
      "startF": 2321,
      "endF": 2349
    },
    {
      "words": [
        {
          "word": "يبقى",
          "startF": 2375,
          "endF": 2387
        },
        {
          "word": "رقمان",
          "startF": 2388,
          "endF": 2407
        },
        {
          "word": "الرسمي",
          "startF": 2414,
          "endF": 2433
        },
        {
          "word": "قرار",
          "startF": 2433,
          "endF": 2449
        }
      ],
      "startF": 2375,
      "endF": 2449
    },
    {
      "words": [
        {
          "word": "يُتخذ",
          "startF": 2449,
          "endF": 2470
        },
        {
          "word": "وسعر",
          "startF": 2477,
          "endF": 2490
        },
        {
          "word": "السوق",
          "startF": 2491,
          "endF": 2504
        },
        {
          "word": "جواب",
          "startF": 2504,
          "endF": 2519
        }
      ],
      "startF": 2449,
      "endF": 2519
    },
    {
      "words": [
        {
          "word": "يُقاس",
          "startF": 2519,
          "endF": 2541
        }
      ],
      "startF": 2519,
      "endF": 2541
    }
  ],
  "handle": "@photonect.news",
  "sourcesLine": "المصادر: هيأة الإحصاء العراقية · البنك المركزي · رويترز · شفق نيوز · تحقيق جمار",
  "endQuestion": "بأي سعر اشتريت آخر مئة دولار؟",
  "totalFrames": 2638
};
