#!/usr/bin/env python3
"""Assemble Essay props from the approved script + generated assets.

- Stages b-roll clips + the rap track into my-video/public/essay/faw-road/
- Computes per-beat durationFrames from approx_seconds (30fps)
- Writes data/essay-faw-road/essay-props.json  (for --props render)
- Writes my-video/src/compositions/Essay/defaultProps.ts  (for Studio preview)
"""
from __future__ import annotations
import json, shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SLUG = "faw-road"
SRC = ROOT / "data" / "essay-faw-road"
SCRIPT = SRC / "script.json"
BROLL = SRC / "broll"
AUDIO_SRC = SRC / "audio" / "rap_1.mp3"   # take 1 (swap to rap_2 if preferred)
PUB = ROOT / "my-video" / "public" / "essay" / SLUG
FPS = 30

ROLE_ORDER = ["hook", "steelman", "turn", "critique", "concession", "reframe", "resolve"]


def main():
    data = json.loads(SCRIPT.read_text())
    segs_in = data["segments"]
    PUB.mkdir(parents=True, exist_ok=True)

    # stage audio
    shutil.copy2(AUDIO_SRC, PUB / "audio.mp3")
    print(f"staged audio → public/essay/{SLUG}/audio.mp3")

    segments = []
    for i, s in enumerate(segs_in, 1):
        role = s["beat_role"]
        clip = BROLL / f"clip_{i}_{role}.mp4"
        if not clip.is_file():
            raise SystemExit(f"missing b-roll: {clip}")
        dst_name = f"clip_{i}_{role}.mp4"
        shutil.copy2(clip, PUB / dst_name)
        dur_frames = round(float(s.get("approx_seconds", 16)) * FPS)
        counters = [
            {
                "value": c.get("value", ""),
                "label_ar": c.get("label_ar", ""),
                "source": c.get("source", ""),
                "as_of": c.get("as_of", ""),
                "unit": c.get("unit", ""),
            }
            for c in s.get("counters", [])
        ]
        segments.append({
            "beat_role": role,
            "arabic_vo": s["arabic_vo"],
            "broll": f"essay/{SLUG}/{dst_name}",
            "brollSeconds": 8,
            "eq_tone": s.get("eq_tone", "cyan"),
            "durationFrames": dur_frames,
            "counters": counters,
        })

    props = {
        "titleArabic": data.get("title_ar", ""),
        "kicker": "تحليل",
        "handle": "@photonect.news",
        "dateLabel": "JUN 27 · 2026",
        "audio": f"essay/{SLUG}/audio.mp3",
        "audioFadeOutFrames": 45,
        "segments": segments,
    }

    out_json = SRC / "essay-props.json"
    out_json.write_text(json.dumps(props, ensure_ascii=False, indent=2))
    print(f"wrote {out_json}")

    ts = ROOT / "my-video" / "src" / "compositions" / "Essay" / "defaultProps.ts"
    ts.write_text(
        "// AUTO-GENERATED by scripts/build_essay_props_2026_06_27.py — do not edit by hand.\n"
        "import type { EssayProps } from \"./schema\";\n\n"
        "export const essayDefaultProps: EssayProps = " + json.dumps(props, ensure_ascii=False, indent=2) + ";\n"
    )
    print(f"wrote {ts}")
    total = sum(s["durationFrames"] for s in segments)
    print(f"segments={len(segments)} totalFrames={total} (~{total/FPS:.0f}s before dissolves)")


if __name__ == "__main__":
    main()
