#!/usr/bin/env python3
"""VOX REEL props builder — narration-first assembly.

Input: a brief JSON with 6 blocks (arabic_vo + collage image + look), plus the
narration audio generated by generate-vo-v11.py. Produces a fully-timed
VoxReel props file: block boundaries snapped to sentence ends, karaoke lines,
and Vox device beats (marker strokes, growing bars) placed on the narration.

Usage:
  python3 scripts/build_vox_props.py data/vox/<slug>/brief.json [--default]
"""
from __future__ import annotations
import argparse, json, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUB = ROOT / "my-video" / "public"
FPS = 30
ENDCARD = 72
PUNCT = "؟?!.،:؛"

# A consistent Vox accent palette across all blocks so the piece reads as one.
PALETTE = [
    {"bg": "#F2E4C9", "accent": "#FFC217"},   # warm paper
    {"bg": "#E8DCC8", "accent": "#D72638"},   # off-white
    {"bg": "#1B2A44", "accent": "#FFC217"},   # deep navy
    {"bg": "#F0E0CD", "accent": "#D72638"},   # paper
    {"bg": "#2A1E2E", "accent": "#FFC217"},   # dark plum
    {"bg": "#F2E4C9", "accent": "#D72638"},   # back to paper — bookend
]


def f(sec: float) -> int:
    return int(round(sec * FPS))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("brief")
    ap.add_argument("--engine", default="edge")
    ap.add_argument("--default", action="store_true")
    args = ap.parse_args()

    brief = json.loads(Path(args.brief).read_text())
    slug = brief["slug"]
    blocks_in = brief["blocks"]
    n = len(blocks_in)

    # ── 1. narration (one continuous read → natural pacing across blocks) ────
    vo_text = " ".join(b["arabic_vo"].strip() for b in blocks_in)
    vo_dir = PUB / "vo" / slug
    r = subprocess.run([sys.executable, str(ROOT / "automation/scripts/generate-vo-v11.py"),
                        "--text", vo_text, "--out-dir", str(vo_dir), "--engine", args.engine],
                       capture_output=True, text=True)
    print(r.stdout.strip())
    if r.returncode != 0:
        sys.exit(f"VO failed (HOLD): {r.stderr.strip()[:400]}")
    wd = json.loads((vo_dir / "words.json").read_text())
    words = [{"word": w["word"], "startF": f(w["start"]), "endF": f(w["end"])} for w in wd["words"]]
    vo_f = f(wd["durationSeconds"])
    total_f = vo_f + ENDCARD

    # ── 2. block boundaries: align to the narration, not a fixed 10s grid ────
    # Walk the word stream and cut each block where its own text ends.
    counts = [len(b["arabic_vo"].split()) for b in blocks_in]
    bounds, idx = [], 0
    for c in counts:
        idx = min(len(words) - 1, idx + c)
        bounds.append(words[idx]["startF"] if idx < len(words) else vo_f)
    bounds[-1] = vo_f + ENDCARD          # last block runs under the end card

    blocks, start = [], 0
    for i, b in enumerate(blocks_in):
        end = bounds[i]
        dur = max(30, end - start)
        pal = PALETTE[i % len(PALETTE)]
        # Vox device beats, placed inside the block
        ann = [{
            "kind": b.get("marker", "circle"),
            "atFrame": int(dur * 0.55), "drawFrames": 15,
            "x": b.get("marker_x", 0.5), "y": b.get("marker_y", 0.44),
            "w": b.get("marker_w", 0.46), "h": b.get("marker_h", 0.26),
            "color": "#0A0A10" if pal["bg"].upper().startswith("#F") or pal["bg"].upper().startswith("#E") else "#FFC217",
        }] if b.get("marker") != "none" else []
        blk = {
            "arabicVo": b["arabic_vo"],
            "collage": f"vox/{slug}/block_{i+1}.jpg",
            "bg": pal["bg"], "accent": pal["accent"],
            "startF": start, "durationF": dur,
            "pushIn": 0.09 + (i % 3) * 0.02,
            "driftX": [-0.02, 0.02, 0][i % 3],
            "annotations": ann,
            "throughline": round((i + 1) / n, 3),   # the gap widens every block
        }
        if b.get("bars"):
            blk["bars"] = {"atFrame": int(dur * 0.35), "values": b["bars"],
                           "x": 0.5, "y": 0.72, "w": 0.5, "h": 0.2, "color": pal["accent"]}
        blocks.append(blk)
        start = end

    # ── 3. karaoke lines (≤4 words, break on punctuation/gaps) ───────────────
    lines, cur = [], []
    for i, w in enumerate(words):
        cur.append(w)
        gap = (words[i + 1]["startF"] - w["endF"]) if i + 1 < len(words) else 999
        if len(cur) >= 4 or w["word"][-1] in PUNCT or gap >= f(0.55):
            lines.append({"words": cur, "startF": cur[0]["startF"], "endF": cur[-1]["endF"]})
            cur = []
    if cur:
        lines.append({"words": cur, "startF": cur[0]["startF"], "endF": cur[-1]["endF"]})

    props = {
        "titleArabic": brief.get("title", ""),
        "vo": f"vo/{slug}/vo.mp3",
        "audioBed": brief.get("audioBed", ""),
        "bedVolume": 0.14,
        "blocks": blocks,
        "lines": lines,
        "handle": "@photonect.news",
        "sourcesLine": brief.get("sourcesLine", ""),
        "endQuestion": brief.get("endQuestion", ""),
        "totalFrames": total_f,
    }

    out_dir = ROOT / "data" / "vox" / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "vox-props.json").write_text(json.dumps(props, ensure_ascii=False, indent=1))
    print(f"✓ {out_dir/'vox-props.json'}")
    print(f"  vo={wd['durationSeconds']:.1f}s total={total_f}f ({total_f/FPS:.1f}s) "
          f"blocks={len(blocks)} lines={len(lines)}")
    for i, b in enumerate(blocks, 1):
        print(f"    block {i}: {b['durationF']/FPS:.1f}s")

    if args.default:
        ts = ROOT / "my-video/src/compositions/VoxReel/defaultProps.ts"
        ts.write_text("// AUTO-GENERATED by scripts/build_vox_props.py\n"
                      'import type { VoxReelProps } from "./schema";\n\n'
                      "export const voxDefaultProps: VoxReelProps = "
                      + json.dumps(props, ensure_ascii=False, indent=2) + ";\n")
        print(f"✓ {ts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
